BKDconf = {
  "report": {     
     "feature":{
        "protein":{
           "type":"protein-feature",
           "ac":{
              "id":"report_ac",
              "vpath":['ac'],
              "type":"hidden"},
           "target":[
                  {"name":"ac",
                   "vpath":['feature','node','ac'],
                   "id":"report_target_ac",
                   "type":"hidden" },
                  {"name":"Protein name",
                   "vpath":['feature','node','name']},
                  {"name":"Gene",
                   "vpath":['feature','node','gene']},
                  {"name":"Taxon",
                   "vpath":['feature','node','taxon'],
                   "type":"taxon" },
                  {"name":"Cross-references",
                   "vpath":['feature','node','xrefs'],
                   "type":"xref",
                   "id":"report_target_feature_node_xrefs",
                   "list":true
                  },
                  {"name":"Sequence variant",
                   "id":"report_target_feature",
                   "list": true,
                   "value":[
                      {"name":"Name",
                      'id':'report_target_feature_label',
                       "vpath":['feature','label'],
                       "edit": true
                      },
                      {
                       "name":"feature_name",
                       "id":'report_target_feature_name',
                       "vpath":['feature','name'],
                       "edit": false,
                       "type": "hidden"
                      },
                      {"name":"Type",
                       "id":"report_target_feature_cvtype",
                       "vpath":['feature','cvType'],
                       "type": 'cvterm',
                       "cvt-list":[{"ns":"psi-mi","ac":"MI:0000","value":"MI:0000","name":"--not specified--"},
                                   {"ns":"psi-mi","ac":"MI:0001","value":"MI:0001","name":"variant"},
                                   {"ns":"psi-mi","ac":"MI:0118","value":"MI:0118","name":"mutation"}],
                       "edit": true

                      },
                      {"name":"GRCh37 coordinate", 
                       "id":"report_target_feature_grch37",
                       "vpath":['feature','grch37'],
                       "edit":true                      
                      },
                      {"name":"GRCh38 coordinate", 
                       "id":"report_target_feature_grch38",
                       "vpath":['feature','grch38'],
                       "edit":true                      
                      },
                      {"name":"Position/Range",
                       "id":'report_target_feature_ranges',
                       "list": true,
                       "edit": true,
                       "vpath":['feature','ranges'],
                       "type": 'range'
                       },
                      {"name":"Cross-references",
                       "id":'report_target_feature_xrefs', 
                       "vpath":['feature','xrefs'],
                       "type":"xref",
                       "xref-ns":[{"ns":"","label":"--not specified--"},
                                  {"ns":"dbsnp","label":"dbSNP"},
                                  {"ns":"omim","label":"OMIM"},
                                  {"ns":"cosmic","label":"Cosmic"},
                                  {"ns":"pubmed","label":"PubMed"}],
                       "xref-type":[{"ns":"psi-mi","ac":"MI:0000","value":"MI:0000",
                                     "name":"--not specified--","label":"--not specified--"},
                                    {"ns":"psi-mi","ac":"MI:0001","value":"MI:0001",
                                     "name":"sequence-variant","label":"Sequence variant"},
                                    {"ns":"dxf","ac":"dxf:0077","value":"dxf:0077",
                                     "name":"has-phenotype","label":"Phenotype"},
                                    {"ns":"dxf","ac":"dxf:0014","value":"dxf:0014",
                                     "name":"described-by","label":"Describes"}],
                       "list":true,
                       "edit": true

                      }]
                  }],
           "value":[ {"name":'Report type',
                      'ns':"cvd",  
                      'ac':"cvd:0000",  
                      'value':'report-channel',
                      'label':'Channel report',
                      'id': 'report_type',
                      "type":"label",
                      "edit": false},
                     {"name":'Channel activation',
                      'ns':"cvd",  
                      'ac':"cvd:0001",  
                      'value':'channel-activation',
                      'id': 'report_value_channel-activation',
                      "type":"text",
                      "edit": true},
                     {"name":'Channel inactivation',
                      'ns':"cvd",  
                      'ac':"cvd:0002",  
                      'id':'report_value_channel-inactivation',
                      'value':'channel-inactivation',
                      "type":"text",
                      "edit": true},
                     {"name":'Channel selectivity',
                      'ns':"cvd",  
                      'ac':"cvd:0003",  
                      'id':'report_value_channel-selectivity',
                      'value':'channel-selectivity',
                      "type":"text",
                      "edit": true},
                     {"name":'Channel expression',
                      'ns':"cvd",  
                      'ac':"cvd:0004",
                      'id':'report_value_channel-expression',
                      'value':'channel-expression',
                      "type":"text",
                      "edit": true},
                     {"name":'Comments',
                      'ns':"cvd",
                      'ac':"cvd:0005",
                      'id':'report_value_comments',
                      'value':'comments',
                       "type":"text",
                       "edit": true}]
        },

        "protein-channel":{
           "type":"protein-feature",
           "ac":{
              "id":"ac",
              "vpath":['ac'],
              "type":"hidden" },
           "target":[
                  {"name":"ac",
                   "vpath":['feature','node','ac'],
                   "id":"report_target_ac",
                   "type":"hidden" },
                  {"name":"Protein name",
                   "vpath":['feature','node','name']},
                  {"name":"Gene",
                   "vpath":['feature','node','gene']},
                  {"name":"Taxon",
                   "vpath":['feature','node','taxon'],
                   "type":"taxon" },
                  {"name":"Cross-references",
                   "vpath":['feature','node','xrefs'],
                   "type":"xref",
                   "id":"report_target_feature_node_xrefs",
                   "list":true
                  },
                  {"name":"Sequence variant",
                   "id":"report_target_feature",
                   "list": true,
                   "value":[
                      {"name":"Name",
                      'id':'report_target_feature_label',
                       "vpath":['feature','label'],
                       "edit": true
                      },
                      {"name":"Type",
                       "id":"report_target_feature_cvtype",
                       "vpath":['feature','cvType'],
                       "type": 'cvterm',
                       "cvt-list":[{"value":"MI:0000","name":"--not specified--"},
                                   {"value":"MI:0001","name":"variant"},
                                   {"value":"MI:0118","name":"mutation"}],
                       "edit": true

                      },
                      {"name":"GRCh37 coordinate", 
                       "id":"report_target_feature_grch37",
                       "vpath":['feature','grch37'],
                       "edit":true                      
                      },
                      {"name":"GRCh38 coordinate", 
                       "id":"report_target_feature_grch38",
                       "vpath":['feature','grch38'],
                       "edit":true                      
                      },
                      {"name":"Position/Range",
                       "id":'report_target_feature_ranges',
                       "list": true,
                       "edit": true,
                       "vpath":['feature','ranges'],
                       "type": 'range'
                       },
                      {"name":"Cross-references",
                       "id":'report_target_feature_xrefs', 
                       "vpath":['feature','xrefs'],
                       "type":"xref",
                       "xref-ns":["--not specified--", "dbSNP","OMIM","Cosmic","PubMed"],
                       "xref-type":[{"value":"MI:0000","name":"--not specified--"},
                                    {"value":"MI:0001","name":"sequence variant"},
                                    {"value":"MI:0002","name":"phenotype"},
                                    {"value":"MI:0002","name":"describes"}],
                       "list":true,
                       "edit": true

                      }]
                  }],
           "value":[ {"name":'Channel activation',
                      'ns':"cvd",  
                      'ac':"cvd:0001",  
                      'value':'channel-activation',
                      'id': 'report_value_channel-activation',
                      "edit": true},
                     {"name":'Channel inactivation',
                      'ns':"cvd",  
                      'ac':"cvd:0002",  
                      'id':'report_value_channel-inactivation',
                      'value':'channel-inactivation',
                      "edit": true},
                     {"name":'Channel selectivity',
                      'ns':"cvd",  
                      'ac':"cvd:0003",  
                      'id':'report_value_channel-selectivity',
                      'value':'channel-selectivity',
                      "edit": true},
                     {"name":'Channel expression',
                      'ns':"cvd",  
                      'ac':"cvd:0004",
                      'id':'report_value_channel-expression',
                      'value':'channel-expression',
                      "edit": true},
                     {"name":'Comments',
                      'ns':"cvd",
                      'ac':"cvd:0005",
                      'id':'report_value_comments',
                      'value':'comments',
                      "edit": true}]
        },

        "protein-transporter":{
           "type":"protein-feature",
           "ac":{
              "id":"ac",
              "vpath":['ac'],
              "type":"hidden"},
           "target":[
                  {"name":"ac",
                   "vpath":['feature','node','ac'],
                   "id":"report_target_ac",
                   "type":"hidden" },
                  {"name":"Protein name",
                   "vpath":['feature','node','name']},
                  {"name":"Gene",
                   "vpath":['feature','node','gene']},
                  {"name":"Taxon",
                   "vpath":['feature','node','taxon'],
                   "type":"taxon" },
                  {"name":"Cross-references",
                   "vpath":['feature','node','xrefs'],
                   "type":"xref",
                   "id":"report_target_feature_node_xrefs",
                   "list":true
                  },
                  {"name":"Sequence variant",
                   "id":"report_target_feature",
                   "list": true,
                   "value":[
                      {"name":"Name",
                      'id':'report_target_feature_label',
                       "vpath":['feature','label'],
                       "edit": true
                      },
                      {"name":"Type",
                       "id":"report_target_feature_cvtype",
                       "vpath":['feature','cvType'],
                       "type": 'cvterm',
                       "cvt-list":[{"value":"MI:0000","name":"--not specified--"},
                                   {"value":"MI:0001","name":"variant"},
                                   {"value":"MI:0118","name":"mutation"}],
                       "edit": true

                      },
                      {"name":"GRCh37 coordinate", 
                       "id":"report_target_feature_grch37",
                       "vpath":['feature','grch37'],
                       "edit":true                      
                      },
                      {"name":"GRCh38 coordinate", 
                       "id":"report_target_feature_grch38",
                       "vpath":['feature','grch38'],
                       "edit":true                      
                      },
                      {"name":"Position/Range",
                       "id":'report_target_feature_ranges',
                       "list": true,
                       "edit": true,
                       "vpath":['feature','ranges'],
                       "type": 'range'
                       },
                      {"name":"Cross-references",
                       "id":'report_target_feature_xrefs', 
                       "vpath":['feature','xrefs'],
                       "type":"xref",
                       "xref-ns":["--not specified--", "dbSNP","OMIM","Cosmic","PubMed"],
                       "xref-type":[{"value":"MI:0000","name":"--not specified--"},
                                    {"value":"MI:0001","name":"sequence variant"},
                                    {"value":"MI:0002","name":"phenotype"},
                                    {"value":"MI:0003","name":"describes"}],
                       "list":true,
                       "edit": true

                      }]
                  }],
           "value":[ {"name":'Channel activation',
                      'ns':"cvd",  
                      'ac':"cvd:0001",  
                      'value':'channel-activation',
                      'id': 'report_value_channel-activation',
                      "edit": true},
                     {"name":'Channel inactivation',
                      'ns':"cvd",  
                      'ac':"cvd:0002",  
                      'id':'report_value_channel-inactivation',
                      'value':'channel-inactivation',
                      "edit": true},
                     {"name":'Channel selectivity',
                      'ns':"cvd",  
                      'ac':"cvd:0003",  
                      'id':'report_value_channel-selectivity',
                      'value':'channel-selectivity',
                      "edit": true},
                     {"name":'Channel expression',
                      'ns':"cvd",  
                      'ac':"cvd:0004",
                      'id':'report_value_channel-expression',
                      'value':'channel-expression',
                      "edit": true},
                     {"name":'Comments',
                      'ns':"cvd",
                      'ac':"cvd:0005",
                      'id':'report_value_comments',
                      'value':'comments',
                      "edit": true}]
        },


        "gene":{
           "fld":[]
        }
     }
  },
  "node":{
        "protein":{
           "fld":[]
         },
         "gene":{
            "fld":[]
         }
     },
     
  "xref-type":[{"ns":"psi-mi","ac":"MI:0000","value":"MI:0000",
                "name":"--not specified--","label":"--not specified--"},
               {"ns":"psi-mi","ac":"MI:0001","value":"MI:0001",
                "name":"sequence-variant","label":"Sequence variant"},
               {"ns":"dxf","ac":"dxf:0077","value":"dxf:0077",
                "name":"has-phenotype","label":"Phenotype"},
               {"ns":"dxf","ac":"dxf:0014","value":"dxf:0014",
                "name":"described-by","label":"Describes"}]
};
                

